version: "3.8"

services:
  credit-service:
    build: ./creditservice
    volumes:
      - ./creditservice:/usr/src/app
    restart: on-failure

  subtract-holds-service:
    build: ./subtractholdsservice
    depends_on:
      - credit-service
      - reserve-proxy
    restart: on-failure

  reserve-proxy:
    image: nginx
    volumes:
      - ./reserveproxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - credit-service